nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link','Authorization']
        max_age: 3600
    paths:
        '^/api/': # toutes les routes commençant par /api/
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: [ 'Content-Type', 'Authorization' ]
            expose_headers: [ 'Link', 'Authorization' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
            max_age: 3600
