GET https://localhost:8000/api/tasks/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDYwOTQ4ODgsImV4cCI6MTc0NjA5ODQ4OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicm9vdEBnbWFpbC5jb20ifQ.CvE5t-SO3P75vQKkFYXdG2RW2nEXtbudTXqlceMOGfdYU6FdRmHv--BfDvgd5Gtx4bi-t0MyvolQI25WPwCs5jixOatufwYFVuYTvyZBAprKy3SGdbpMBfYsvVvxzQLZqFRQCjMYXlWg9BZSxDm7p_8xhpoo76rt521jPrSDQRz6zQr6kBHYbMVD5daJElREuzpvaoAz85WOvNTSmYmD2Bucwnmz-ezIpNgzjRgpdPcrfmCzBwFRiipkgleR6Bcw3FaUOAzlKEv91BTwurZX4bajEU1n8D-LubCjEOQ4JioV5NoOz-J3FAWS2ZnzfXmyTDpYpleg5rwUDHjtv_M5YQ
###

GET https://localhost:8000/api/tasks/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDYwOTQ4ODgsImV4cCI6MTc0NjA5ODQ4OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicm9vdEBnbWFpbC5jb20ifQ.CvE5t-SO3P75vQKkFYXdG2RW2nEXtbudTXqlceMOGfdYU6FdRmHv--BfDvgd5Gtx4bi-t0MyvolQI25WPwCs5jixOatufwYFVuYTvyZBAprKy3SGdbpMBfYsvVvxzQLZqFRQCjMYXlWg9BZSxDm7p_8xhpoo76rt521jPrSDQRz6zQr6kBHYbMVD5daJElREuzpvaoAz85WOvNTSmYmD2Bucwnmz-ezIpNgzjRgpdPcrfmCzBwFRiipkgleR6Bcw3FaUOAzlKEv91BTwurZX4bajEU1n8D-LubCjEOQ4JioV5NoOz-J3FAWS2ZnzfXmyTDpYpleg5rwUDHjtv_M5YQ

###

POST  https://localhost:8000/api/tasks/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDYwOTQ4ODgsImV4cCI6MTc0NjA5ODQ4OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicm9vdEBnbWFpbC5jb20ifQ.CvE5t-SO3P75vQKkFYXdG2RW2nEXtbudTXqlceMOGfdYU6FdRmHv--BfDvgd5Gtx4bi-t0MyvolQI25WPwCs5jixOatufwYFVuYTvyZBAprKy3SGdbpMBfYsvVvxzQLZqFRQCjMYXlWg9BZSxDm7p_8xhpoo76rt521jPrSDQRz6zQr6kBHYbMVD5daJElREuzpvaoAz85WOvNTSmYmD2Bucwnmz-ezIpNgzjRgpdPcrfmCzBwFRiipkgleR6Bcw3FaUOAzlKEv91BTwurZX4bajEU1n8D-LubCjEOQ4JioV5NoOz-J3FAWS2ZnzfXmyTDpYpleg5rwUDHjtv_M5YQ

{
  "title": "cuisine",
  "description": "Description 0"
}
###

PATCH https://localhost:8000/api/tasks/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDYwOTQ4ODgsImV4cCI6MTc0NjA5ODQ4OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicm9vdEBnbWFpbC5jb20ifQ.CvE5t-SO3P75vQKkFYXdG2RW2nEXtbudTXqlceMOGfdYU6FdRmHv--BfDvgd5Gtx4bi-t0MyvolQI25WPwCs5jixOatufwYFVuYTvyZBAprKy3SGdbpMBfYsvVvxzQLZqFRQCjMYXlWg9BZSxDm7p_8xhpoo76rt521jPrSDQRz6zQr6kBHYbMVD5daJElREuzpvaoAz85WOvNTSmYmD2Bucwnmz-ezIpNgzjRgpdPcrfmCzBwFRiipkgleR6Bcw3FaUOAzlKEv91BTwurZX4bajEU1n8D-LubCjEOQ4JioV5NoOz-J3FAWS2ZnzfXmyTDpYpleg5rwUDHjtv_M5YQ


{
  "title": "cuisine roumaine 34"
}
###
DELETE https://localhost:8000/api/tasks/13
###

POST https://localhost:8000/api/login_check
Content-Type: application/json
Accept: application/json

{
 "email": "root@gmail.com",
  "password":"root"
}





