GET https://localhost:8000/api/tasks/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDU5Mjc4NjEsImV4cCI6MTc0NTkzMTQ2MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicm9vdEBnbWFpbC5jb20ifQ.szy4IgT3Wq3RDkPfhHRckONSjRoI7c6WGiIq54Kjfx2v77meQW-XZLKcruopgpZpYdEmeCppO23fFNUUsTXxmJOU47fVy2akkphFOlZSbwBBBPQlM3EezpDJL6_RzJHm5KK9L1dj3VFPca5XHPxJbzrCIyi3bOYv7qdS5gTbKX01FFtLQuj-J0vbXMFSILSjyUOa7iNtWd03kohvAZWoK-J5Ut0Oi3FkkYIgcRWbZ0SuFsBUgemU3LLP7znS4iHE1VZ5gdwvpzplx2cUCMNftLhOZ3ocidxZTo840AvYAT5W2DhdR2Znje008i2khASQctDvV-RvDzRKJsem7I5rOQ

###

GET https://localhost:8000/api/tasks/1
###

POST  https://localhost:8000/api/tasks/
Content-Type: application/json

{
  "title": "cuisine",
  "description": "Description 0"
}
###

PATCH https://localhost:8000/api/tasks/1
Content-Type: application/json

{
  "title": "cuisine roumaine",
  "description": "Description 0"
}
###
DELETE https://localhost:8000/api/tasks/13
###

POST https://localhost:8000/api/login_check
Content-Type: application/json
Accept: application/json

{

}





